# Generated by Django 5.0 on 2024-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_pictures/'),
        ),
    ]
